name: Build and test smart contracts

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
      GHA_PAT:
        required: true
jobs:
  build:
    runs-on: cloudwalk-k8s-runner
    name: Check code style and run tests

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions return after update that file everywhere
          cache: npm
          registry-url: "https://npm.pkg.github.com"
          scope: "@cloudwalk"

      - name: Copy .env file
        run: cp .env.example .env

      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHA_PAT }}

      - run: npm run build

      - run: npm run prettier:check

      - run: npm run eslint:check

      - run: npm run test

      - name: run coverage action
        uses: cloudwalk/brlc-dev-ex/.github/actions/coverage@main
        with:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
